apiVersion: v1
kind: Namespace
metadata:
  name: prometheus-dev
spec:
  finalizers:
    - kubernetes
status:
  phase: Active
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: quota
  namespace: prometheus-dev
spec:
  hard:
    pods: "10"
    limits.memory: 2Gi
    requests.cpu: "2"
    requests.memory: 2Gi
    requests.storage: 6Gi
    resourcequotas: "1"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: prometheus-storage
  namespace: prometheus-dev
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
